/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clasefile.ui;

import com.mycompany.clasefile.model.Discos;
import com.mycompany.clasefile.model.es_teclado.ESTeclado;
import com.mycompany.clasefile.model.g_ficheros.GFicheros;
import com.mycompany.clasefile.ui.child_panel.buscarDirectorio;
import com.mycompany.clasefile.ui.child_panel.crearDirectorio;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author carlo
 */
public class file_ui extends javax.swing.JFrame {

    //List Model
    private DefaultListModel dflCarpetas = new DefaultListModel();
    ;
    
    //Table Model
    
    static String[] datosDiscos = {"Unidad", "Ocupado", "Total", "Libre"};
    Object[][] dataDiscos = new Object[0][0];
    
    static String[] datosFicheros = {"Unidad", "Ocupado", "Total", "Libre"};
    Object[][] dataFicheros = new Object[0][0];

    private DefaultTableModel dftDiscos = new DefaultTableModel(dataDiscos, datosDiscos);

    private DefaultTableModel dflFicheros = new DefaultTableModel(dataFicheros, datosFicheros);
    
    private ArrayList<File> listDirectorios = new ArrayList<File>();
   
    private ArrayList<File> listFicheros = new ArrayList<File>();

    private ArrayList<Discos> almacenDiscos = new ArrayList<Discos>();  
    
    private GFicheros gFicheros = new GFicheros();

    private ESTeclado esTeclado = new ESTeclado();

    public String ruta = "";
    
    public file_ui() {
        initComponents();
        list_subcarpetas.setModel(dflCarpetas);
        tbl_discos.setModel(dftDiscos);

        Discos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_subcarpetas = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_discos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_ficheros = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_subcarpetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_subcarpetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_subcarpetas);

        tbl_discos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Unidad", "Ocupado", "Total", "Libre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_discos);

        jLabel1.setText("Carpetas");

        jLabel2.setText("Discos");

        tbl_ficheros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_ficheros);

        jLabel3.setText("Ficheros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jMenu1.setText("Filtrar");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opciones");

        jMenuItem1.setText("Eliminar");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Crear");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Buscar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca de");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked

        buscarDirectorio buscar = new buscarDirectorio(this, true);
        buscar.setVisible(true);
       // menuBuscarFicheros();

    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked


    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void list_subcarpetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_subcarpetasMouseClicked
    
    }//GEN-LAST:event_list_subcarpetasMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        if(list_subcarpetas.getSelectedIndex() != -1){
              crearDirectorio crear = new crearDirectorio(this, true);
              crear.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null, "Por favor seleccione una carpeta",
                "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(file_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(file_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(file_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(file_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new file_ui().setVisible(true);
            }
        });
    }

    private void Discos() {
        almacenDiscos = gFicheros.getUnidades();
        insertarDiscos();
    }

    //Rellenar la tabla de discos con los discos instalados de nuestro ordenador
    private void insertarDiscos() {
        Object[] fila = new Object[datosDiscos.length];


        for (int i = 0; i < almacenDiscos.size(); i++) {
            fila[0] = almacenDiscos.get(i).getUnidad();
            fila[1] = almacenDiscos.get(i).getAlmacenamientoOcupado();
            fila[2] = almacenDiscos.get(i).getAlmacenamientoTotal();
            fila[3] = almacenDiscos.get(i).getAlmacenamientoDisponible();

            dftDiscos.addRow(fila);
        }

    }

    //Menu para buscar nuestros directorios por carpetas
    public void menuBuscarFicheros(String ruta) {
        getDirectorios(ruta);
    }

    //Adicion de ficheros en nuestro JList
    private void getDirectorios(String ruta) {
        dflCarpetas.clear();
        ruta = ruta;
        try{
         listDirectorios = gFicheros.getDir(ruta);
       
            for (int i = 0; i < listDirectorios.size(); i++) {
                dflCarpetas.addElement(listDirectorios.get(i));
            }   
        }catch(Exception e){
              dflCarpetas.addElement("No existen Carpetas");
        }
    }
    
    public void buscarFicheros(String ruta){
        listFicheros = gFicheros.getFicheros(ruta);
        for(File l: listFicheros){
            
        }
    }

    public void getFicheros(String nombre){
        String carpeta = dflCarpetas.getElementAt(list_subcarpetas.getSelectedIndex()).toString();
        gFicheros.nuevoDirectorio(ruta+carpeta, nombre);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> list_subcarpetas;
    private javax.swing.JTable tbl_discos;
    private javax.swing.JTable tbl_ficheros;
    // End of variables declaration//GEN-END:variables
}
